# Build stage
FROM node:18.17.1-alpine3.18 AS build
WORKDIR /frontend
COPY package*.json ./
COPY .env.prod ./.env
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:1.25.2-alpine
# Copy the custom NGINX configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
