version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    
    networks:
      - mynetwork

networks:
  mynetwork: