version: '3.8'

services:
  frontend:
    image: dlovric2/academify-frontend:latest
    ports:
      - "3000:80" 
    depends_on:
      - backend
    networks:
      - mynetwork
  
  backend:
    image: dlovric2/academify-backend:latest
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    container_name: backend

networks:
  mynetwork:
